name: userprofile-CI
on:
  pull_request:
    branches: [master]
    paths:
      - apis/userprofile/**
      - .github/workflows/userprofile-CI.yml

  push:
    branches: [ch3]
    paths:
      - apis/userprofile/**
      - .github/workflows/userprofile-CI.yml

defaults:
  run:
    working-directory: apis/userprofile/

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    # from the docs.  Not needed (but cool)  since we will build
    # into a container with the correct version later
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }} # container uses 8.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
